# Generated by Django 2.1.7 on 2019-03-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingSubmits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('task_id', models.IntegerField()),
                ('verdict', models.CharField(max_length=200)),
                ('programmingLanguage', models.CharField(max_length=200)),
                ('timeConsumedMillis', models.IntegerField()),
                ('memoryConsumedBytes', models.IntegerField()),
            ],
        ),
    ]
