# Generated by Django 2.1.7 on 2019-03-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0002_programmingsubmits'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmingsubmits',
            name='codeforcesSubmitId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
