# Generated by Django 2.1.7 on 2019-03-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0003_programmingsubmits_codeforcessubmitid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmingsubmits',
            name='userid',
        ),
        migrations.AddField(
            model_name='programmingsubmits',
            name='username',
            field=models.CharField(default='CoffeBee', max_length=200),
        ),
    ]
