# Generated by Django 2.1.7 on 2019-04-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0004_auto_20190327_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskprogrammingpurchases',
            name='userid',
        ),
        migrations.AddField(
            model_name='taskprogrammingpurchases',
            name='username',
            field=models.CharField(default='CoffeBee', max_length=200),
        ),
    ]
