# Generated by Django 2.1.7 on 2019-04-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0005_auto_20190412_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskprogrammingpurchases',
            name='item_id',
        ),
        migrations.AddField(
            model_name='taskprogrammingpurchases',
            name='item_level',
            field=models.IntegerField(default=1),
        ),
    ]
