# Generated by Django 2.1.7 on 2019-04-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathematics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MathSubmits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='CoffeBee', max_length=100)),
                ('answer', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=5000)),
                ('verdict', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='taskmathematicspurchases',
            name='userid',
        ),
        migrations.AddField(
            model_name='taskmathematicspurchases',
            name='username',
            field=models.CharField(default='CoffeBee', max_length=100),
        ),
    ]
