# Generated by Django 2.1.7 on 2019-04-17 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mathematics', '0002_auto_20190417_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathsubmits',
            name='judge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
