# Generated by Django 2.1.7 on 2019-04-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathematics', '0003_mathsubmits_judge'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathsubmits',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
