# Generated by Django 2.1.7 on 2019-04-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathematics', '0004_mathsubmits_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmathematicspurchases',
            name='item_id',
        ),
        migrations.AddField(
            model_name='taskmathematicspurchases',
            name='item_level',
            field=models.IntegerField(default=1),
        ),
    ]
