# Generated by Django 2.1.7 on 2019-03-08 14:12

from django.db import migrations, models
import tasks.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCTF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('level', models.IntegerField()),
                ('hash_link', models.CharField(default=tasks.models.TaskCTF.create_hash, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TaskMathematics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('level', models.IntegerField()),
                ('hash_link', models.CharField(default=tasks.models.TaskMathematics.create_hash, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TaskProgramming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('level', models.IntegerField()),
                ('hash_link', models.CharField(default=tasks.models.TaskProgramming.create_hash, max_length=200)),
            ],
        ),
    ]
