# Generated by Django 2.1.7 on 2019-04-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20190310_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskprogramming',
            name='statement',
            field=models.FileField(default='', upload_to='tasks/'),
            preserve_default=False,
        ),
    ]
