# Generated by Django 2.1.7 on 2019-04-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_taskprogramming_statement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskprogramming',
            name='statement',
            field=models.FileField(upload_to='tasks/statement/'),
        ),
    ]
