# Generated by Django 2.1.7 on 2019-04-17 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0005_auto_20190412_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmathematics',
            name='judge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskmathematics',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
