# Generated by Django 2.1.7 on 2019-04-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20190417_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmathematics',
            name='statement',
            field=models.FileField(default='tasks/statement/7bbb0bd4934ded248d83051a33c986', upload_to='tasks/statement/'),
        ),
    ]
