# Generated by Django 2.1.7 on 2019-04-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20190417_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmathematics',
            name='answer',
            field=models.CharField(default='1', max_length=20),
        ),
    ]
