# Generated by Django 2.1.7 on 2019-04-19 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_auto_20190419_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskctf',
            name='judge',
        ),
    ]
